# update-obstacles.ps1
# assets/runner/obstacle-*.svg 를 스캔해서
# css/runner.css 와 js/games/runner.js 를 자동 갱신합니다.

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

function ConvertTo-CssDataUrl([string]$Path) {
    $raw = Get-Content $Path -Raw -Encoding UTF8
    $raw = $raw -replace '"', "'"
    $raw = ($raw -split '\r?\n' | ForEach-Object { $_.Trim() } | Where-Object { $_ }) -join ' '
    $raw = $raw -replace '<', '%3C' -replace '>', '%3E' -replace '#', '%23'
    return "url(`"data:image/svg+xml,$raw`")"
}

function Write-Header([string]$text) {
    Write-Host ""
    Write-Host "═══════════════════════════════════════" -ForegroundColor DarkCyan
    Write-Host "  $text" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════" -ForegroundColor DarkCyan
}

function Write-Ok([string]$msg)   { Write-Host "  [OK]  $msg" -ForegroundColor Green }
function Write-Fail([string]$msg) { Write-Host "  [ERR] $msg" -ForegroundColor Red }
function Write-Info([string]$msg) { Write-Host "  [..] $msg"  -ForegroundColor Gray }

# ── 1. SVG 파일 스캔 ──────────────────────────────────────────
Write-Header "장애물 SVG 스캔"

$svgFiles = Get-ChildItem "$root/assets/runner/obstacle-*.svg" | Sort-Object Name
if ($svgFiles.Count -eq 0) {
    Write-Fail "assets/runner/obstacle-*.svg 파일을 찾을 수 없습니다."
    Write-Host ""; exit 1
}
$newGlyphs = @($svgFiles | ForEach-Object { $_.BaseName -replace '^obstacle-', '' })
Write-Ok "SVG 파일 $($svgFiles.Count)개 발견"

# ── 2. 기존 등록 목록 읽기 ────────────────────────────────────
$jsPath  = "$root/js/games/runner.js"
$jsText  = [System.IO.File]::ReadAllText($jsPath, [System.Text.Encoding]::UTF8)
$oldGlyphs = @()
if ($jsText -match "runnerObstacleGlyphs = \[([^\]]+)\]") {
    $oldGlyphs = @($Matches[1] -split "',\s*'" -replace "^'" -replace "'$" |
                   ForEach-Object { $_.Trim().Trim("'") } |
                   Where-Object { $_ })
}

# ── 3. 변경 내역 표시 ─────────────────────────────────────────
Write-Header "변경 내역"

$added   = $newGlyphs | Where-Object { $_ -notin $oldGlyphs }
$removed = $oldGlyphs | Where-Object { $_ -notin $newGlyphs }
$kept    = $newGlyphs | Where-Object { $_ -in    $oldGlyphs }

if ($added.Count -eq 0 -and $removed.Count -eq 0) {
    Write-Info "장애물 목록 변경 없음 (SVG 내용은 갱신됩니다)"
} else {
    foreach ($g in $added)   { Write-Host "  [ADD] $g" -ForegroundColor Green }
    foreach ($g in $removed) { Write-Host "  [DEL] $g" -ForegroundColor Yellow }
}
foreach ($g in $kept) { Write-Info "유지: $g" }

# ── 4. SVG → data URL 인코딩 ──────────────────────────────────
Write-Header "SVG 인코딩"

$imageVars = [ordered]@{}
$encodeOk = $true
foreach ($file in $svgFiles) {
    $name = $file.BaseName -replace '^obstacle-', ''
    try {
        $imageVars[$name] = ConvertTo-CssDataUrl $file.FullName
        Write-Ok "$name  ($([math]::Round($file.Length/1KB, 1)) KB)"
    } catch {
        Write-Fail "$name 인코딩 실패: $_"
        $encodeOk = $false
    }
}
if (-not $encodeOk) { Write-Host ""; exit 1 }

# ── 5. runner.css 업데이트 ────────────────────────────────────
Write-Header "runner.css 갱신"

try {
    $cssPath = "$root/css/runner.css"
    $css = [System.IO.File]::ReadAllText($cssPath, [System.Text.Encoding]::UTF8)

    if ($css -notmatch '--runner-player-image:([^;]+);') { throw '--runner-player-image 없음' }
    $playerUrl = $Matches[1].Trim()

    $rootVars = "  --runner-player-image:$playerUrl;"
    foreach ($name in $imageVars.Keys) { $rootVars += "`n  --runner-$name-image:$($imageVars[$name]);" }
    $css = [regex]::Replace($css, '(?s):root\s*\{[^}]*\}', ":root {`n$rootVars`n}")

    $cssLines = ($css -split '\r?\n') | Where-Object { $_ -notmatch '\.runner-obstacle\[data-glyph=' }
    $css = $cssLines -join "`n"

    $rules = ($newGlyphs | ForEach-Object {
        ".runner-obstacle[data-glyph=`"$_`"] { --runner-obstacle-image:var(--runner-$_-image); }"
    }) -join "`n"
    $css = [regex]::Replace($css, '(?m)^(\.runner-obstacle-unit\s*\{[^}]+\})', "`$1`n$rules")
    $css = [regex]::Replace($css, '\n{3,}', "`n`n")

    [System.IO.File]::WriteAllText($cssPath, $css, [System.Text.Encoding]::UTF8)
    Write-Ok ":root 변수 $($imageVars.Count + 1)개 (player 포함)"
    Write-Ok "[data-glyph] 규칙 $($newGlyphs.Count)개"
} catch {
    Write-Fail "CSS 갱신 실패: $_"
    Write-Host ""; exit 1
}

# ── 6. runner.js 업데이트 ────────────────────────────────────
Write-Header "runner.js 갱신"

try {
    $arr = "'" + ($newGlyphs -join "', '") + "'"
    $jsText = [regex]::Replace(
        $jsText,
        '(const|let) runnerObstacleGlyphs = \[[^\]]*\];[^\n]*',
        "const runnerObstacleGlyphs = [$arr]; // auto-generated by update-obstacles.ps1"
    )
    [System.IO.File]::WriteAllText($jsPath, $jsText, [System.Text.Encoding]::UTF8)
    Write-Ok "runnerObstacleGlyphs = [$arr]"
} catch {
    Write-Fail "JS 갱신 실패: $_"
    Write-Host ""; exit 1
}

# ── 완료 ──────────────────────────────────────────────────────
Write-Host ""
Write-Host "═══════════════════════════════════════" -ForegroundColor DarkGreen
Write-Host "  완료!  장애물 $($newGlyphs.Count)개 등록됨" -ForegroundColor Green
Write-Host "═══════════════════════════════════════" -ForegroundColor DarkGreen
