'use strict';

(function () {
  let runnerFrame = null;
  let runnerRunToken = 0;
  let runnerRunning = false;
  let runnerHolding = false;
  let runnerPointerDown = false;
  let runnerRestartArmed = true;
  let runnerIgnoreNextClick = false;
  let runnerY = 0;
  let runnerVelocity = 0;
  let runnerHoldMs = 0;
  let runnerSpeed = 0;
  let runnerScore = 0;
  let runnerLastFrame = 0;
  const runnerObstacleGlyphs = ['bars', 'command', 'cross', 'grid', 'square']; // auto-generated by update-obstacles.ps1
  const RUNNER_MAX_DIFFICULTY_SCORE = 500;
  const RUNNER_REFERENCE_STAGE_HEIGHT = 155;
  const RUNNER_MAX_EMPTY_SECONDS = 0.72;
  const RUNNER_COLLISION_GRACE_SCORE = 3;
  let runnerObstacles = [];
  let runnerAirObstacleCount = 0;
  let runnerGroundObstacleCount = 0;
  let runnerStageWidth = 0;
  let runnerStageHeight = 0;

  let runnerPlayerGeometry = {
    hitLeft: 0,
    hitBottom: 0,
    hitWidth: 0,
    hitHeight: 0
  };
  const RUNNER_PLAYER_HIT_INSET_RATIO = 0.065;

  function stopRunner(hideObstacles = true) {
    runnerRunToken++;
    if (runnerFrame !== null) cancelAnimationFrame(runnerFrame);
    runnerFrame = null;
    runnerRunning = false;
    runnerHolding = false;
    if (hideObstacles) {
      $('#runner-stage')?.removeAttribute('data-running');
      clearRunnerHitboxDebug();
    }
  }

  function scheduleRunnerFrame() {
    const token = runnerRunToken;
    runnerFrame = requestAnimationFrame(frameTime => {
      if (token !== runnerRunToken) return;
      runnerFrame = null;
      runRunner(frameTime);
    });
  }

  function resetRunnerPreview() {
    runnerScore = 0;
    runnerPointerDown = false;
    runnerRestartArmed = true;
    runnerIgnoreNextClick = false;
    $('#runner-score').textContent = '';
    $('#runner-player').style.transform = 'translateY(0)';
    $('#runner-hitbox-player').style.transform = 'translateY(0)';
    $('#runner-obstacle').style.left = '0px';
    $('#runner-obstacle-next').style.left = '0px';
    $('#runner-obstacle-tail').style.left = '0px';
    runnerObstacles = [];
    runnerStageWidth = 0;
    runnerStageHeight = 0;
    clearRunnerHitboxDebug();
  }

  function runnerJump() {
    const stage = $('#runner-stage');
    const stageHeight = stage?.clientHeight || RUNNER_REFERENCE_STAGE_HEIGHT;
    const physicsScale = stageHeight / RUNNER_REFERENCE_STAGE_HEIGHT;
    if (!runnerRunning || runnerY > stageHeight * 0.006) return;
    runnerVelocity = 285 * physicsScale;
    runnerHoldMs = 0;
  }

  function runnerOverscan(stageHeight) {
    return stageHeight * 1.35;
  }

  function runnerSafeGap(previous, obstacle, stageWidth, speed) {
    // 5단계 거리 판단: 이전 장애물과 현재 장애물의 조합에 따른 물리적 최소 안전 시간
    let requiredSeconds = Math.max(previous.recoverySeconds || 0.85, obstacle.entrySeconds || 0.80);

    // [억까 방지 1] 지상 -> 공중: 지상을 넘으려고 점프한 플레이어가 바닥에 완전히 착지한 뒤 공중에 진입해야 함
    if (previous.placement === 'ground' && obstacle.placement === 'air') {
      const extraAirLargeBuffer = obstacle.size === 'large' ? 1.20 : 0.98;
      requiredSeconds = Math.max(requiredSeconds, (previous.size === 'large' ? 1.25 : extraAirLargeBuffer));
    }
    // [억까 방지 2] 공중 -> 지상: 공중 장애물 밑을 지나간 뒤 반응하여 점프할 시간 확보
    else if (previous.placement === 'air' && obstacle.placement === 'ground') {
      requiredSeconds = Math.max(requiredSeconds, (obstacle.size === 'large' ? 0.95 : 0.82));
    }
    // [억까 방지 3] 지상 대형 -> 지상 대형: 연속 높은 점프 시 착지 후 재입력 버퍼
    else if (previous.placement === 'ground' && obstacle.placement === 'ground' && (previous.size === 'large' || obstacle.size === 'large')) {
      requiredSeconds = Math.max(requiredSeconds, 1.02);
    }

    const idealGap = speed * requiredSeconds;
    // 화면이 너무 텅 비지 않게 하되, 물리적으로 필요한 최소 안전 시간(idealGap)은 절대 깎지 않음
    const maxGap = Math.max(idealGap, stageWidth + speed * RUNNER_MAX_EMPTY_SECONDS);
    return Math.min(idealGap, maxGap);
  }

  function syncRunnerPlayerGeometry(width, height) {
    const playerNode = $('#runner-player');
    const playerWidth = playerNode?.offsetWidth || (width * 0.075);
    const playerHeight = playerNode?.offsetHeight || (height * 0.17);
    const playerLeft = width * 0.12;
    const inset = playerWidth * RUNNER_PLAYER_HIT_INSET_RATIO;
    const groundHeight = height * (0.004 / 0.38); // aligns with calc(var(--square) * .004) ground line
    runnerPlayerGeometry = {
      hitLeft: playerLeft + inset,
      hitBottom: groundHeight + inset,
      hitWidth: Math.max(1, playerWidth - inset * 2),
      hitHeight: Math.max(1, playerHeight - inset * 2)
    };
    const hitboxPlayer = $('#runner-hitbox-player');
    if (hitboxPlayer) {
      hitboxPlayer.style.left = `${runnerPlayerGeometry.hitLeft}px`;
      hitboxPlayer.style.bottom = `${runnerPlayerGeometry.hitBottom}px`;
      hitboxPlayer.style.width = `${runnerPlayerGeometry.hitWidth}px`;
      hitboxPlayer.style.height = `${runnerPlayerGeometry.hitHeight}px`;
      hitboxPlayer.style.transform = `translateY(${-runnerY}px)`;
    }
  }

  function syncRunnerStageSize(width, height) {
    if (!width || !height) return;
    syncRunnerPlayerGeometry(width, height);
    if (!runnerStageWidth || !runnerStageHeight) {
      runnerStageWidth = width;
      runnerStageHeight = height;
      return;
    }
    if (Math.abs(width - runnerStageWidth) < 0.5 && Math.abs(height - runnerStageHeight) < 0.5) return;

    const horizontalScale = width / runnerStageWidth;
    const verticalScale = height / runnerStageHeight;
    runnerY *= verticalScale;
    runnerVelocity *= verticalScale;
    runnerObstacles.forEach(obstacle => {
      obstacle.x *= horizontalScale;
      obstacle.bottom *= verticalScale;
      obstacle.fontSize *= verticalScale;
      obstacle.node.style.left = `${obstacle.x}px`;
      obstacle.node.style.bottom = `${obstacle.bottom}px`;
      obstacle.node.style.fontSize = `${obstacle.fontSize}px`;
      measureRunnerObstacle(obstacle);
      obstacle.previousX = undefined;
      obstacle.previousGeneration = null;
    });
    runnerStageWidth = width;
    runnerStageHeight = height;
  }

  function renderRunner() {
    const transform = `translateY(${-runnerY}px)`;
    $('#runner-player').style.transform = transform;
    const hitboxPlayer = $('#runner-hitbox-player');
    if (hitboxPlayer) hitboxPlayer.style.transform = transform;
    runnerObstacles.forEach(obstacle => {
      obstacle.node.style.left = `${obstacle.x}px`;
    });
    $('#runner-score').textContent = tr(`${Math.floor(runnerScore)}점`, `${Math.floor(runnerScore)} pts`);
  }

  function setRunnerObstacleGlyph(obstacle, glyphType, repeatCount = 1) {
    obstacle.glyphType = glyphType;
    obstacle.visualRepeats = repeatCount;
    obstacle.node.dataset.glyph = glyphType;
  }

  function measureRunnerObstacle(obstacle) {
    const fontSize = Math.max(1, obstacle.fontSize || 16);
    const repeatCount = Math.max(1, obstacle.visualRepeats || 1);
    const baseUnitSize = fontSize * 0.78;
    const gap = baseUnitSize * 0.08;
    const node = obstacle.node;
    const scales = obstacle.unitScales || null;

    while (node.childElementCount < repeatCount) {
      const unit = document.createElement('span');
      unit.className = 'runner-obstacle-unit';
      node.append(unit);
    }
    while (node.childElementCount > repeatCount) {
      node.lastElementChild.remove();
    }

    let totalWidth = 0;
    let maxHeight = baseUnitSize;
    const unitHitBoxes = [];

    Array.from(node.children).forEach((unit, idx) => {
      const scale = (scales && scales[idx]) ? scales[idx] : 1;
      const uSize = baseUnitSize * scale;
      unit.style.setProperty('--unit-size', `${uSize}px`);
      unitHitBoxes.push({
        xOffset: totalWidth,
        width: uSize,
        height: uSize
      });
      totalWidth += uSize;
      if (uSize > maxHeight) maxHeight = uSize;
      if (idx < repeatCount - 1) totalWidth += gap;
    });

    obstacle.width = totalWidth;
    obstacle.height = maxHeight;
    obstacle.unitHitBoxes = unitHitBoxes;

    node.style.setProperty('--runner-obstacle-unit', `${baseUnitSize}px`);
    node.style.gap = `${gap}px`;
    node.style.width = `${obstacle.width}px`;
    node.style.height = `${obstacle.height}px`;
  }

  function runnerPlayerHitBox() {
    const bottom = runnerY + runnerPlayerGeometry.hitBottom;
    return {
      left: runnerPlayerGeometry.hitLeft,
      right: runnerPlayerGeometry.hitLeft + runnerPlayerGeometry.hitWidth,
      bottom,
      top: bottom + runnerPlayerGeometry.hitHeight
    };
  }

  function runnerObstacleHitBox(obstacle) {
    return {
      left: obstacle.x,
      right: obstacle.x + obstacle.width,
      bottom: obstacle.bottom,
      top: obstacle.bottom + obstacle.height
    };
  }

  // 볼록 언덕 등 유닛별 실제 정밀 히트박스 목록 반환
  function runnerObstacleSubBoxes(obstacle) {
    if (!obstacle.unitHitBoxes || obstacle.unitHitBoxes.length <= 1) {
      return [runnerObstacleHitBox(obstacle)];
    }
    return obstacle.unitHitBoxes.map(u => ({
      left: obstacle.x + u.xOffset,
      right: obstacle.x + u.xOffset + u.width,
      bottom: obstacle.bottom,
      top: obstacle.bottom + u.height
    }));
  }

  function positionRunnerHitboxDebug(node, box) {
    node.style.left = `${box.left}px`;
    node.style.bottom = `${box.bottom}px`;
    node.style.width = `${Math.max(1, box.right - box.left)}px`;
    node.style.height = `${Math.max(1, box.top - box.bottom)}px`;
    node.style.display = '';
  }

  function clearRunnerHitboxDebug() {
    $('#runner-stage')?.removeAttribute('data-hitbox-ready');
    document.querySelectorAll('.runner-hitbox-obstacle-dynamic').forEach(n => n.remove());
  }

  // 모든 세부 서브박스(유닛 블록별 실제 판정선)를 화면에 정확히 표시
  function renderRunnerHitboxDebug(obstacleSubBoxes) {
    const stage = $('#runner-stage');
    if (!stage) return;

    // 기본 정적 3개 디버그 노드는 숨김 처리
    ['#runner-hitbox-obstacle', '#runner-hitbox-obstacle-next', '#runner-hitbox-obstacle-tail'].forEach(sel => {
      const el = $(sel);
      if (el) el.style.display = 'none';
    });

    let pool = Array.from(stage.querySelectorAll('.runner-hitbox-obstacle-dynamic'));

    // 필요한 만큼 동적 디버그 노드 생성
    while (pool.length < obstacleSubBoxes.length) {
      const d = document.createElement('div');
      d.className = 'runner-hitbox-debug runner-hitbox-obstacle runner-hitbox-obstacle-dynamic';
      d.setAttribute('aria-hidden', 'true');
      stage.append(d);
      pool.push(d);
    }

    obstacleSubBoxes.forEach((box, index) => {
      positionRunnerHitboxDebug(pool[index], box);
    });

    // 남는 노드는 숨김
    for (let i = obstacleSubBoxes.length; i < pool.length; i++) {
      pool[i].style.display = 'none';
    }

    stage.dataset.hitboxReady = 'true';
  }

  function runnerHitBoxesIntersect(playerBox, obstacleBox) {
    return obstacleBox.left < playerBox.right
      && obstacleBox.right > playerBox.left
      && playerBox.top > obstacleBox.bottom
      && playerBox.bottom < obstacleBox.top;
  }

  function buildRunnerObstacle(obstacle, stageWidth, stageHeight, x) {
    obstacle.x = x;
    obstacle.node.style.left = `${x}px`;
    obstacle.node.style.transform = 'none';
    obstacle.generation = (obstacle.generation || 0) + 1;
    obstacle.previousX = undefined;
    obstacle.previousGeneration = null;

    const difficulty = Math.min(1, runnerScore / RUNNER_MAX_DIFFICULTY_SCORE);

    // ==========================================
    // 1단계: 장애물 스킨 랜덤 선택
    // ==========================================
    const glyph = runnerObstacleGlyphs[Math.floor(Math.random() * runnerObstacleGlyphs.length)] || 'square';

    // ==========================================
    // 2단계: 지상 장애물인지 공중 장애물인지 선택
    // ==========================================
    // 공중 장애물이 너무 자주 나오지 않도록 제한 (공중 비율 최대 28%, 연속 공중 방지)
    const canSpawnAir = runnerAirObstacleCount < runnerGroundObstacleCount * 1.5;
    const airChance = difficulty > 0.15 ? (0.16 + difficulty * 0.12) : 0;
    const placement = (canSpawnAir && Math.random() < airChance) ? 'air' : 'ground';
    obstacle.placement = placement;

    if (placement === 'air') {
      runnerAirObstacleCount++;
    } else {
      runnerGroundObstacleCount++;
    }

    // ==========================================
    // 3단계: 장애물 크기 선택
    // 지상 4종: xs(초소형), small(소형), medium(중형), large(대형)
    // 공중 2종: small(중간 공중-넘거나 통과), large(상단 거대 공중-무조건 통과)
    // ==========================================
    let size = 'small';
    const sizeRoll = Math.random();

    if (placement === 'ground') {
      if (difficulty > 0.25 && sizeRoll < 0.20 + difficulty * 0.15) {
        size = 'large';  // 최고 높이 점프 필수
      } else if (sizeRoll < 0.45 + difficulty * 0.15) {
        size = 'medium'; // 중간 점프
      } else if (sizeRoll < 0.75) {
        size = 'small';  // 일반 점프
      } else {
        size = 'xs';     // 초소형 점프
      }
    } else {
      // 공중: 초반엔 선택형(small) 위주, 난이도 오르면 점프 금지 대형(large) 출현
      size = (difficulty > 0.20 && sizeRoll < 0.35 + difficulty * 0.20) ? 'large' : 'small';
    }
    obstacle.size = size;

    // 크기에 따른 물리 스펙 매핑
    const groundHeight = stageHeight * (0.004 / 0.30);
    let heightRatio = 0.16;
    let entrySec = 0.75;
    let recoverySec = 0.85;

    if (placement === 'ground') {
      obstacle.bottom = groundHeight;
      if (size === 'large') {
        heightRatio = 0.33 + difficulty * 0.05; // 33% (최고 풀점 필수)
        entrySec = 0.95;
        recoverySec = 1.15;
      } else if (size === 'medium') {
        heightRatio = 0.24 + difficulty * 0.03; // 24% (중간 점프)
        entrySec = 0.82;
        recoverySec = 0.95;
      } else if (size === 'small') {
        heightRatio = 0.17 + difficulty * 0.02; // 17% (기본 점프)
        entrySec = 0.72;
        recoverySec = 0.85;
      } else { // 'xs'
        heightRatio = 0.11 + difficulty * 0.02; // 11% (초소형 점프)
        entrySec = 0.65;
        recoverySec = 0.75;
      }
    } else {
      if (size === 'small') {
        // [공중 소형: 선택형]
        // 바닥 22% 높이에 떠 있음 (플레이어 키 17%보다 높아 아래로 쏙 지나감)
        // 두께 10% (상단 끝 32%로 플레이어 풀점프 정점 42%보다 낮아 위로 뛰어넘기도 가능!)
        heightRatio = 0.10;
        obstacle.bottom = groundHeight + stageHeight * 0.22;
        entrySec = 0.80;
        recoverySec = 0.88;
      } else {
        // [공중 대형: 상단~중단 완벽 차폐 (무조건 가만히 지나가야 함)]
        // 머리 바로 위(21%)부터 상단(75% 이상)까지 가려서 점프 시 100% 충돌
        heightRatio = 0.48 + difficulty * 0.06;
        obstacle.bottom = groundHeight + stageHeight * 0.21;
        entrySec = 0.90;
        recoverySec = 0.95;
      }
    }

    const fontSize = stageHeight * heightRatio * 1.25;
    obstacle.height = fontSize;
    obstacle.fontSize = fontSize;
    obstacle.node.style.bottom = `${obstacle.bottom}px`;
    obstacle.node.style.fontSize = `${fontSize}px`;
    obstacle.node.style.height = '';

    // ==========================================
    // 4단계: 장애물 반복 횟수 선택 (1~4 사이)
    // 크기와 속도에 따른 비거리 한계 완벽 검토
    // ==========================================
    let repeats = Math.floor(Math.random() * 4) + 1; // 1, 2, 3, 4
    const isEarlyGame = difficulty < 0.35;

    if (placement === 'ground') {
      if (size === 'large') {
        // 대형: 초반 1개 고정, 중후반 최대 2개 (3개 이상은 풀점 비거리 초과)
        repeats = isEarlyGame ? 1 : Math.min(repeats, 2);
      } else if (size === 'medium') {
        // 중형: 초반 최대 2개, 중후반 최대 3개 (초반 3개는 풀점 착지점에 걸림)
        repeats = isEarlyGame ? Math.min(repeats, 2) : Math.min(repeats, 3);
      } else if (size === 'small') {
        // 소형: 초반 최대 3개, 중후반 최대 4개
        repeats = isEarlyGame ? Math.min(repeats, 3) : repeats;
      } else { // 'xs'
        // 초소형: 높이가 낮아 초반/후반 모두 1~4개 자유롭게 통과 가능
        repeats = repeats;
      }
    } else {
      if (size === 'small') {
        // 공중 소형은 플레이어가 위로 뛰어넘는 선택도 가능해야 하므로 점프 비거리 고려 최대 2개
        repeats = Math.min(repeats, 2);
      } else {
        // 공중 대형은 서서 안전하게 지나가므로 1~4개 모두 자유롭게 출현 가능
        repeats = isEarlyGame ? Math.min(repeats, 2) : repeats;
      }
    }

    // [볼록 언덕 패턴]: 바닥 초소형/소형이 3개 이상 반복될 때 가운데 1~2개를 한 단계 크게 만들어 볼록하게 구성
    let unitScales = null;
    if (placement === 'ground' && (size === 'xs' || size === 'small') && repeats >= 3) {
      if (Math.random() < 0.75) { // 75% 확률로 볼록 패턴 적용
        if (repeats === 3) {
          unitScales = [1.0, 1.40, 1.0]; // 가운데 1개가 약 40% 커짐
        } else if (repeats === 4) {
          unitScales = [1.0, 1.35, 1.35, 1.0]; // 가운데 2개가 약 35% 커짐
        }
      }
    }
    obstacle.unitScales = unitScales;

    // 반복 횟수에 따른 진입/회복 보정
    entrySec += (repeats - 1) * 0.05;
    recoverySec += (repeats - 1) * 0.06;
    obstacle.entrySeconds = entrySec;
    obstacle.recoverySeconds = recoverySec;

    // ==========================================
    // 렌더링 동기화 및 측정
    // ==========================================
    setRunnerObstacleGlyph(obstacle, glyph, repeats);
    measureRunnerObstacle(obstacle);
  }

  function endRunner() {
    stopRunner(false);
    runnerRestartArmed = !runnerPointerDown;
    const score = Math.floor(runnerScore);
    saveBest('runner', score);
    showBest('runner');
    setState('idle', tr('다시 달리기', 'Run again'), tr(`${score}점! 탭해서 다시 시작`, `${score} pts! Tap to run again`));
  }

  function runRunner(frameTime) {
    if (!runnerRunning || current !== 'runner') return;
    const elapsed = Math.max(0, Math.min(40, frameTime - runnerLastFrame)) / 1000;
    runnerLastFrame = frameTime;
    const stage = $('#runner-stage');
    const width = stage.clientWidth;
    const height = stage.clientHeight;
    if (!width || !height) { scheduleRunnerFrame(); return; }
    syncRunnerStageSize(width, height);

    const physicsScale = height / RUNNER_REFERENCE_STAGE_HEIGHT;
    if (runnerHolding && runnerVelocity > 0 && runnerHoldMs < 220) {
      runnerVelocity += 680 * physicsScale * elapsed;
      runnerHoldMs += elapsed * 1000;
    }
    runnerVelocity -= 850 * physicsScale * elapsed;
    runnerY += runnerVelocity * elapsed;
    if (runnerY <= 0) {
      runnerY = 0;
      runnerVelocity = 0;
      if (runnerHolding) runnerJump();
    }
    const difficulty = Math.min(1, runnerScore / RUNNER_MAX_DIFFICULTY_SCORE);
    const endlessSpeedBonus = Math.log1p(Math.max(0, runnerScore - RUNNER_MAX_DIFFICULTY_SCORE) / 500) * 0.05;
    runnerSpeed = width * (0.44 + difficulty * 0.76 + endlessSpeedBonus);
    runnerScore += elapsed * 10;

    runnerObstacles.forEach(obstacle => { obstacle.recycledThisFrame = false; });
    runnerObstacles.forEach(obstacle => { obstacle.x -= runnerSpeed * elapsed; });
    runnerObstacles.forEach(obstacle => {
      const overscan = runnerOverscan(height);
      if (obstacle.x + obstacle.width >= -overscan) return;
      const previous = runnerObstacles.filter(item => item !== obstacle).reduce((furthest, item) => (
        item.x + item.width > furthest.x + furthest.width ? item : furthest
      ));
      const stagingX = width + overscan;
      buildRunnerObstacle(obstacle, width, height, stagingX);
      obstacle.recycledThisFrame = true;
      const safeGap = runnerSafeGap(previous, obstacle, width, runnerSpeed);
      obstacle.x = Math.max(stagingX, previous.x + previous.width + safeGap);
      obstacle.node.style.left = `${obstacle.x}px`;
    });

    renderRunner();
    const playerBox = runnerPlayerHitBox();
    const allSubBoxes = runnerObstacles.flatMap(obstacle => runnerObstacleSubBoxes(obstacle));
    renderRunnerHitboxDebug(allSubBoxes);
    const hit = runnerScore >= RUNNER_COLLISION_GRACE_SCORE && runnerObstacles.some(obstacle => {
      if (obstacle.recycledThisFrame) return false;
      const subBoxes = runnerObstacleSubBoxes(obstacle);

      // 세부 박스(유닛 블록) 중 하나라도 플레이어와 닿았는지 검사
      return subBoxes.some(box => {
        if (runnerHitBoxesIntersect(playerBox, box)) return true;
        const verticalOverlap = playerBox.top > box.bottom && playerBox.bottom < box.top;
        if (!verticalOverlap) return false;
        if (obstacle.previousX === undefined || obstacle.previousGeneration !== obstacle.generation) return false;
        const xOffset = box.left - obstacle.x;
        const minX = Math.min(obstacle.previousX + xOffset, box.left);
        const maxX = Math.max(obstacle.previousX + xOffset + (box.right - box.left), box.right);
        return maxX > playerBox.left && minX < playerBox.right;
      });
    });
    if (hit) {
      endRunner();
      return;
    }
    runnerObstacles.forEach((obstacle) => {
      if (obstacle.recycledThisFrame) {
        obstacle.previousX = undefined;
        obstacle.previousGeneration = null;
        return;
      }
      obstacle.previousX = obstacle.x;
      obstacle.previousGeneration = obstacle.generation;
    });
    scheduleRunnerFrame();
  }

  function startRunner() {
    const stage = $('#runner-stage');
    const width = stage.clientWidth;
    const height = stage.clientHeight;
    if (!width || !height) return;

    stopRunner(false);
    clearRunnerHitboxDebug();
    stage.dataset.running = 'true';
    runnerRunning = true;
    runnerRestartArmed = false;
    runnerHolding = false;
    runnerY = 0;
    runnerVelocity = 0;
    runnerHoldMs = 0;
    runnerSpeed = width * 0.44;
    runnerScore = 0;
    runnerAirObstacleCount = 0;
    runnerGroundObstacleCount = 0;
    runnerLastFrame = performance.now();
    runnerStageWidth = width;
    runnerStageHeight = height;
    runnerObstacles = [
      { node: $('#runner-obstacle') },
      { node: $('#runner-obstacle-next') },
      { node: $('#runner-obstacle-tail') }
    ];

    const entryX = width + runnerSpeed * 0.7;
    const stagingX = width + runnerOverscan(height);
    buildRunnerObstacle(runnerObstacles[0], width, height, entryX);
    buildRunnerObstacle(runnerObstacles[1], width, height, stagingX);
    runnerObstacles[1].x = runnerObstacles[0].x + runnerObstacles[0].width + runnerSafeGap(runnerObstacles[0], runnerObstacles[1], width, runnerSpeed);
    runnerObstacles[1].node.style.left = `${runnerObstacles[1].x}px`;
    buildRunnerObstacle(runnerObstacles[2], width, height, stagingX);
    runnerObstacles[2].x = runnerObstacles[1].x + runnerObstacles[1].width + runnerSafeGap(runnerObstacles[1], runnerObstacles[2], width, runnerSpeed);
    runnerObstacles[2].node.style.left = `${runnerObstacles[2].x}px`;

    $('#message').textContent = tr('짧게: 낮은 점프 · 꾹: 최고 점프 연속', 'Tap: low jump · Hold: repeat high jumps');
    state = 'playing';
    document.body.dataset.state = 'idle';
    syncRunnerPlayerGeometry(width, height);
    renderRunner();
    renderRunnerHitboxDebug(runnerObstacles.flatMap(obstacle => runnerObstacleSubBoxes(obstacle)));
    scheduleRunnerFrame();
  }

  function init() {
    resetRunnerPreview();
    setState('idle', tr('눌러서 시작', 'Tap to start'), tr('짧게 점프 · 꾹 누르면 연속 점프', 'Tap to jump · hold to repeat jump'));
  }

  function onAction() {
    if (runnerIgnoreNextClick) {
      runnerIgnoreNextClick = false;
      return;
    }
    if (!runnerRunning && runnerRestartArmed) {
      startRunner();
    }
  }

  function onPointerDown(event) {
    event.preventDefault();
    runnerPointerDown = true;
    if (!runnerRunning) {
      if (runnerRestartArmed) startRunner();
    } else {
      runnerHolding = true;
      runnerJump();
    }
  }

  function onPointerUp() {
    runnerPointerDown = false;
    runnerHolding = false;
    if (!runnerRunning) {
      runnerRestartArmed = true;
      runnerIgnoreNextClick = true;
    }
  }

  function onKeyDown(event) {
    event.preventDefault();
    if (!runnerRunning) {
      if (runnerRestartArmed) startRunner();
      return;
    }
    if (event.repeat) return;
    runnerHolding = true;
    runnerJump();
  }

  function onKeyUp(event) {
    event.preventDefault();
    runnerHolding = false;
    if (!runnerRunning) {
      runnerRestartArmed = true;
    }
  }

  function onResize() {
    if (!runnerObstacles.length) return;
    const stage = $('#runner-stage');
    syncRunnerStageSize(stage.clientWidth, stage.clientHeight);
    renderRunner();
    renderRunnerHitboxDebug(runnerObstacles.flatMap(obstacle => runnerObstacleSubBoxes(obstacle)));
  }

  function onCancel() {
    stopRunner();
    resetRunnerPreview();
  }

  function onVisibilityChange(isHidden) {
    if (isHidden && runnerRunning) {
      stopRunner();
      runnerPointerDown = false;
      runnerRestartArmed = true;
      runnerIgnoreNextClick = false;
      setState('idle', tr('다시 시작', 'Try again'), tr('잠시 멈췄어요', 'Round paused'));
    }
  }

  registerGame('runner', {
    init,
    onAction,
    onPointerDown,
    onPointerUp,
    onKeyDown,
    onKeyUp,
    onResize,
    onCancel,
    onVisibilityChange
  });
})();
